services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nuvem}
      MYSQL_USER: ${MYSQL_USER:-projeto}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-projeto}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Patoto123}
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ilacf/app-nuvem:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE:-nuvem}
      DB_USER: ${MYSQL_USER:-projeto}
      DB_PASSWORD: ${MYSQL_PASSWORD:-projeto}
      DATABASE_URL: mysql+pymysql://${MYSQL_USER:-projeto}:${MYSQL_PASSWORD:-projeto}@${DB_HOST:-db}:${DB_PORT:-3306}/${DB_DATABASE:-nuvem}
      SENHA_SECRETA: ${SENHA_SECRETA}
    ports:
      - 8000:8000
    restart: always