site_name: "Projeto Nuvem - Documentação Completa"
theme:
  features:
    - tabs
  name: "material"
  language: "pt"
  palette:
    primary: "cyan"
    accent: "lilac"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tabbed
  - attr_list

plugins:
  - search